export const API_ENDPOINT = process.env.REACT_APP_API_ENDPOINT;

export const START_LOADING = 'START_LOADING';
export const FINISH_LOADING = 'FINISH_LOADING';

export const REGISTER = 'USERS_REGISTER';
export const REGISTER_SUCCESS = 'USERS_REGISTER_SUCCESS';
export const LOGIN = 'USERS_LOGIN';
export const LOGIN_SUCCESS = 'USERS_LOGIN_SUCCESS';
export const LOGOUT = 'USERS_LOGOUT';

export const GET_ALL_USERS = 'GET_ALL_USERS';
export const SET_USERS_LIST = 'SET_USERS_LIST';
export const ADD_USER = 'ADD_USER';
export const USER_ADDED = 'USER_ADDED';
export const DELETE_USER = 'DELETE_USER';
export const USER_DELETED = 'USER_DELETED';
export const UPDATE_USER = 'UPDATE_USER';
export const USER_UPDATED = 'USER_UPDATED';

export const GET_ALL_RESTAURANTS = 'GET_ALL_RESTAURANTS';
export const SET_RESTAURANTS_LIST = 'SET_RESTAURANTS_LIST';
export const GET_RESTAURANT = 'GET_RESTAURANT';
export const SET_CURRENT_RESTAURANT = 'SET_CURRENT_RESTAURANT';
export const ADD_RESTAURANT = 'ADD_RESTAURANT';
export const DELETE_RESTAURANT = 'DELETE_RESTAURANT';
export const UPDATE_RESTAURANT = 'UPDATE_RESTAURANT';

export const GET_ALL_REVIEWS = 'GET_ALL_REVIEWS';
export const SET_REVIEWS = 'SET_REVIEWS';
export const GET_REVIEW = 'GET_REVIEW';
export const SET_CURRENT_REVIEW = 'SET_CURRENT_REVIEW';
export const ADD_REVIEW = 'ADD_REVIEW';
export const DELETE_REVIEW = 'DELETE_REVIEW';
export const UPDATE_REVIEW = 'UPDATE_REVIEW';
export const FETCH_PENDING_REVIEWS = 'FETCH_PENDING_REVIEWS';
export const SET_PENDING_REVIEWS = 'SET_PENDING_REVIEWS';
export const SUBMIT_REPLY = 'SUBMIT_REPLY';
